sandbox/config/routes.rb
Sandbox::Application.routes.draw do
 

  resources :pineapple_steps

  match "/pineapple.js" => "pineapple#show", :as => :pineapple_engine
  match "/pineapple" => "pineapple#steps", :as => :pineapple_steps_engine
  
end

sandbox/app/models/pineapple_step.rb
class PineappleStep < ActiveRecord::Base
end

sandbox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

sandbox/app/controllers/pineapple_controller.rb
require "pineapple/translator"

class PineappleController < ApplicationController
  
  def show 
    render :layout => false
  end

  def steps
    current_step = nil
    if params['init'].nil? || params['init'] == ""
      current_step = session[:next_step]
    else
      current_step = params['init']
    end
    unless current_step.nil?
      pineapple_step = PineappleStep.find_by_name current_step
      step_body = pineapple_step.body
      translator = PineappleTranslator.new(step_body)
      translator.translate
      session[:next_step] = translator.next_s
      puts "next step = #{translator.next_s}"
      render :inline => translator.script
    else
      render :inline => ""
    end
  end

 
end

sandbox/app/controllers/pineapple_steps_controller.rb
class PineappleStepsController < ApplicationController
  # GET /pineapple_steps
  # GET /pineapple_steps.xml
  def index
    @pineapple_steps = PineappleStep.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pineapple_steps }
      format.json{
        render :json => @pineapple_steps.to_json
      }
    end
  end

  # GET /pineapple_steps/1
  # GET /pineapple_steps/1.xml
  def show
    @pineapple_step = PineappleStep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pineapple_step }
      format.json{
        render :json => @pineapple_step.to_json
      }
    end
  end

  # GET /pineapple_steps/new
  # GET /pineapple_steps/new.xml
  def new
    @pineapple_step = PineappleStep.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pineapple_step }
      
    end
  end

  # GET /pineapple_steps/1/edit
  def edit
    @pineapple_step = PineappleStep.find(params[:id])
  end

  # POST /pineapple_steps
  # POST /pineapple_steps.xml
  def create
    @pineapple_step = PineappleStep.new(params[:pineapple_step])

    respond_to do |format|
      if @pineapple_step.save
        format.html { redirect_to(@pineapple_step, :notice => 'Pineapple step was successfully created.') }
        format.xml  { render :xml => @pineapple_step, :status => :created, :location => @pineapple_step }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pineapple_step.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pineapple_steps/1
  # PUT /pineapple_steps/1.xml
  def update
    @pineapple_step = PineappleStep.find(params[:id])

    respond_to do |format|
      if @pineapple_step.update_attributes(params[:pineapple_step])
        format.html { redirect_to(@pineapple_step, :notice => 'Pineapple step was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pineapple_step.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pineapple_steps/1
  # DELETE /pineapple_steps/1.xml
  def destroy
    @pineapple_step = PineappleStep.find(params[:id])
    @pineapple_step.destroy

    respond_to do |format|
      format.html { redirect_to(pineapple_steps_url) }
      format.xml  { head :ok }
    end
  end
end

sandbox/app/helpers/application_helper.rb
module ApplicationHelper
  def pineapple_script
   engine_path =    pineapple_engine_path
   engine_path= "#{engine_path}?init=#{params['initp']}" unless params['initp'].nil?   
   engine_path
  end
end

sandbox/app/helpers/pineapple_steps_helper.rb
module PineappleStepsHelper
end

sandbox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.5.1.min' %>
  
  "<script src='<%= pineapple_script %>' type='text/javascript'></script>"

  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>
 
</body>
</html>

sandbox/app/views/pineapple_steps/_form.html.erb
<%= form_for(@pineapple_step) do |f| %>
  <% if @pineapple_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pineapple_step.errors.count, "error") %> prohibited this pineapple_step from being saved:</h2>

      <ul>
      <% @pineapple_step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sandbox/app/views/pineapple_steps/edit.html.erb
<h1>Editing pineapple_step</h1>

<%= render 'form' %>

<%= link_to 'Show', @pineapple_step %> |
<%= link_to 'Back', pineapple_steps_path %>

sandbox/app/views/pineapple_steps/index.html.erb
<h1>Listing pineapple_steps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pineapple_steps.each do |pineapple_step| %>
  <tr>
    <td><%= pineapple_step.name %></td>
    <td><%= pineapple_step.body %></td>
    <td><%= link_to 'Show', pineapple_step %></td>
    <td><%= link_to 'Edit', edit_pineapple_step_path(pineapple_step) %></td>
    <td><%= link_to 'Destroy', pineapple_step, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pineapple step', new_pineapple_step_path %>

sandbox/app/views/pineapple_steps/new.html.erb
<h1>New pineapple_step</h1>

<%= render 'form' %>

<%= link_to 'Back', pineapple_steps_path %>

sandbox/app/views/pineapple_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pineapple_step.name %>
</p>

<p>
  <b>Body:</b>
  <%= @pineapple_step.body %>
</p>


<%= link_to 'Edit', edit_pineapple_step_path(@pineapple_step) %> |
<%= link_to 'Back', pineapple_steps_path %>